services:
  - type: web
    name: student-life-hub-api
    runtime: docker
    plan: free
    dockerContext: StudentLifeHub  
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"